apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
type: Opaque
stringData:
  .htpasswd: |
{{ .Values.basicAuth.htpasswd | indent 4 }}
